CREATE TABLE IF NOT EXISTS delivery
(
    delivery_id integer NOT NULL DEFAULT nextval('delivery_delivery_id_seq'::regclass),
    tracking_number character varying(50) COLLATE pg_catalog."default",
    delivery_price numeric,
    delivery_status character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT delivery_pkey PRIMARY KEY (delivery_id)
)

CREATE TABLE IF NOT EXISTS public.games
(
    game_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    publisher character varying(100) COLLATE pg_catalog."default",
    genre character varying(50) COLLATE pg_catalog."default",
    condition character varying(10) COLLATE pg_catalog."default",
    image_url character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT games_pkey PRIMARY KEY (game_id),
    CONSTRAINT unique_game_name UNIQUE (name),
    CONSTRAINT games_condition_check CHECK (condition::text = ANY (ARRAY['New'::character varying, 'Like New'::character varying, 'Used'::character varying, 'Damaged'::character varying]::text[]))
)

CREATE TABLE IF NOT EXISTS public.listings
(
    listing_id integer NOT NULL DEFAULT nextval('listings_listing_id_seq'::regclass),
    game_id integer NOT NULL,
    user_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    condition character varying(10) COLLATE pg_catalog."default",
    price numeric,
    rate_per_day numeric,
    is_rent character(1) COLLATE pg_catalog."default",
    isavailable boolean DEFAULT true,
    CONSTRAINT listings_pkey PRIMARY KEY (listing_id),
    CONSTRAINT listings_game_id_fkey FOREIGN KEY (game_id)
        REFERENCES public.games (game_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT listings_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT listings_condition_check CHECK (condition::text = ANY (ARRAY['New'::character varying, 'Like New'::character varying, 'Used'::character varying, 'Damaged'::character varying]::text[])),
    CONSTRAINT listings_is_rent_check CHECK (is_rent = ANY (ARRAY['Y'::bpchar, 'N'::bpchar]))
)


CREATE TABLE IF NOT EXISTS public.purchases
(
    purchase_id integer NOT NULL DEFAULT nextval('purchases_purchase_id_seq'::regclass),
    listing_id integer NOT NULL,
    purchaser_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    delivery_id integer,
    CONSTRAINT purchases_pkey PRIMARY KEY (purchase_id),
    CONSTRAINT purchases_delivery_id_fkey FOREIGN KEY (delivery_id)
        REFERENCES public.delivery (delivery_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT purchases_listing_id_fkey FOREIGN KEY (listing_id)
        REFERENCES public.listings (listing_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT purchases_purchaser_id_fkey FOREIGN KEY (purchaser_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public.rentals
(
    rental_id integer NOT NULL DEFAULT nextval('rentals_rental_id_seq'::regclass),
    listing_id integer NOT NULL,
    rentee_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    delivery_id integer,
    start_date date,
    end_date date,
    CONSTRAINT rentals_pkey PRIMARY KEY (rental_id),
    CONSTRAINT rentals_delivery_id_fkey FOREIGN KEY (delivery_id)
        REFERENCES public.delivery (delivery_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT rentals_listing_id_fkey FOREIGN KEY (listing_id)
        REFERENCES public.listings (listing_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT rentals_rentee_id_fkey FOREIGN KEY (rentee_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public.users
(
    user_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    city character varying(50) COLLATE pg_catalog."default",
    address character varying(100) COLLATE pg_catalog."default",
    phone_number character varying(15) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email)
)


insert into users (user_id, first_name, last_name, city, address, phone_number,email,password)
values ('U001', 'Agha', 'saqlain', 'quetta', 'alamdar road', 123, 'agha@iba', 'admin');
insert into users (user_id, first_name, last_name, city, address, phone_number,email,password)
values ('U002', 'saqlain', 'kazmi', 'quetta', 'berori', 03108459082, 's.saqlain.26869@khi.iba.edu.pk', 'saqlain');
insert into users (user_id, first_name, last_name, city, address, phone_number,email,password)
values ('U003', 'saim', 'wajid', 'karachi', 'sadr', 03333333333, 'saim@iba', 'saim');
insert into users (user_id, first_name, last_name, city, address, phone_number,email,password)
values ('U004', 'shazain', 'qureshi', 'hayderabad', 'pata nhi', 032145678, 'shazain.27115@khi.isba.edu.pk', 'shazain');


//email : agha@iba
//password : admin

//s.saqlain.26869@khi.iba.edu.games_pk
//saqlain

//saim@iba
//saim

//shazain.27115@khi.iba.edu.pk
//shazain